### ISSUE TITLE
Disable buttons if not in use...

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/RobotsGoHome#11]

**Comment by Option4Studios** [comment]
I have made them interactable = false, when they are 'locked'

still need to check whether can stop the eventTriggers...

**Comment by Option4Studios** [comment]
have fixed in the start level overlay - need to work out code for actual level boosters...

**Comment by Option4Studios** [comment]
done! :O)

**Comment by Rich-Option4Studios** [comment]
So far I think this is occuring. Will flag any instances from now if occur
