### ISSUE TITLE
BUTTONS: Stop getting larger on select/hover?

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/RobotsGoHome#15]

**Comment by Option4Studios** [comment]
I think   fixing errors and stopping the button being interactable if 'locked' has stopped this error

**Comment by Option4Studios** [comment]
It's better but not quite 100% fixed on the Menu at least.  Managed to make the boosters and Play button get bigger.  Selecting the green/red circles on the booster seems to be one way of making the booster grow.

**Comment by Option4Studios** [comment]
Another test and clicking on the green/red circles causes the booster button to no longer get big when hover over it. The Play/Facebook buttons are a tiny bit bigger.

**Comment by Rich-Option4Studios** [comment]
Another test and clicking on the green/red circles causes the booster button to no longer get big when hover over it. The Play/Facebook buttons are a tiny bit bigger.

**Comment by Option4Studios** [comment]
All booster buttons in menu and level now stay at their correct size...
Please double check the play button in start level overlay within menu
