### ISSUE TITLE
MENU: robots disappear on Play overlay

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/RobotsGoHome#24]
Robots disappear after clicking add booster on Play overlay and then closing booster overlay

**Comment by Option4Studios** [comment]
-[ ]

**Comment by Option4Studios** [comment]
I think removing an error has fixed this - there was a localisation var call to a button text title that didn't exist - moved the code into the level script

**Comment by Option4Studios** [comment]
If you buy a booster on level 2+ and return to level 1 and click buy a booster, the robots disappear. This does not seem to occur on any other level

**Comment by Rich-Option4Studios** [comment]
If you buy a booster on level 2+ and return to level 1 and click buy a booster, the robots disappear. This does not seem to occur on any other level

**Comment by Option4Studios** [comment]
This was due to the booster of the highest level being available, but conflicting with the boosters of that level - so couldn't find the correct overlay to show...
Have set so only the boosters that were originally available are available if the player returns to a level at a later date
